# Generated by Django 5.2.7 on 2026-04-29 00:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ODS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_usuario', models.IntegerField(choices=[(1, 'Aluno'), (2, 'Professor'), (3, 'Coordenador')], default=1)),
                ('ra', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_projeto', models.CharField(max_length=255)),
                ('nome_autores', models.TextField()),
                ('objetivos_trabalho', models.TextField()),
                ('metodologia_projeto', models.TextField()),
                ('resultados_projeto', models.TextField()),
                ('justificativa_ods', models.TextField()),
                ('reflexao_projeto', models.TextField()),
                ('referencia_projeto', models.TextField(blank=True, null=True)),
                ('status_projeto', models.IntegerField(choices=[(0, 'Rascunho'), (1, 'Em análise'), (2, 'Aprovado'), (3, 'Rejeitado')], default=0)),
                ('aluno', models.ForeignKey(limit_choices_to={'tipo_usuario': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to=settings.AUTH_USER_MODEL)),
                ('ods', models.ManyToManyField(related_name='projetos', to='plataformaResumosAPP.ods')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos', to='plataformaResumosAPP.programa')),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField(choices=[(1, '1º Semestre'), (2, '2º Semestre')])),
                ('coordenador', models.ForeignKey(limit_choices_to={'tipo_usuario': 3}, on_delete=django.db.models.deletion.PROTECT, related_name='semestres_coordenados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ano', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('semestre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revista', to='plataformaResumosAPP.semestre')),
            ],
        ),
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_submissao', models.IntegerField(choices=[(0, 'Em análise'), (1, 'Aprovado'), (2, 'Rejeitado')], default=0)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('data_submissao', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissoes', to='plataformaResumosAPP.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_turma', models.CharField(max_length=100)),
                ('codigo_acesso', models.CharField(max_length=20, unique=True)),
                ('disciplina', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=255)),
                ('responsavel', models.ForeignKey(limit_choices_to={'tipo_usuario': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='turmas_responsavel', to=settings.AUTH_USER_MODEL)),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='plataformaResumosAPP.semestre')),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='plataformaResumosAPP.turma'),
        ),
        migrations.CreateModel(
            name='ProjetoRevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revistas', to='plataformaResumosAPP.projeto')),
                ('revista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_revista', to='plataformaResumosAPP.revista')),
            ],
            options={
                'unique_together': {('revista', 'projeto')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='projeto',
            unique_together={('aluno', 'turma')},
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(limit_choices_to={'tipo_usuario': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='plataformaResumosAPP.turma')),
            ],
            options={
                'unique_together': {('aluno', 'turma')},
            },
        ),
    ]
