# Generated by Django 5.2.7 on 2025-10-20 22:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EdicaoRevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_revista', models.CharField(max_length=255, unique=True)),
                ('data_fechamento_submissoes', models.DateField(blank=True, null=True)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('arquivo_pdf', models.FileField(blank=True, max_length=255, null=True, upload_to='revistas/pdfs/', verbose_name='PDF da Revista')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('AUTOR', 'Autor'), ('REVISOR', 'Revisor'), ('ADMIN', 'Administrador')], default='AUTOR', max_length=20, verbose_name='Tipo de Permissão')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_autores', models.JSONField(default=list, help_text='Lista de co-autores em formato JSON.')),
                ('referencia_projeto', models.JSONField(default=list, help_text='Lista de referências bibliográficas em formato JSON/BibTeX.')),
                ('titulo_projeto', models.CharField(max_length=255)),
                ('programa_pepict', models.CharField(blank=True, max_length=255, null=True)),
                ('ods_projeto', models.CharField(blank=True, max_length=255, null=True)),
                ('objetivos_trabalho', models.TextField()),
                ('metodologia_projeto', models.TextField()),
                ('resultados_projeto', models.TextField()),
                ('reflexao_projeto', models.TextField()),
                ('status_projeto', models.CharField(choices=[('em_edicao', 'Em Edição'), ('submetido', 'Submetido para Revisão'), ('aprovado', 'Aprovado para Publicação'), ('rejeitado', 'Rejeitado / Requer Revisão')], default='em_edicao', max_length=50, verbose_name='Status de Publicação')),
                ('data_submissao', models.DateTimeField(blank=True, null=True)),
                ('data_ultima_atualizacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_autorados', to=settings.AUTH_USER_MODEL, verbose_name='Autor Principal')),
            ],
        ),
        migrations.CreateModel(
            name='EdicaoRevista_Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_na_revista', models.IntegerField(default=1)),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformaResumosAPP.edicaorevista')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformaResumosAPP.projeto')),
            ],
            options={
                'ordering': ['edicao', 'ordem_na_revista'],
                'unique_together': {('edicao', 'projeto')},
            },
        ),
        migrations.AddField(
            model_name='edicaorevista',
            name='projetos',
            field=models.ManyToManyField(related_name='edicoes_publicadas', through='plataformaResumosAPP.EdicaoRevista_Projetos', to='plataformaResumosAPP.projeto'),
        ),
        migrations.CreateModel(
            name='RevisaoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_revisao', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentários do Revisor')),
                ('data_revisao', models.DateTimeField(blank=True, null=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='plataformaResumosAPP.projeto')),
                ('revisor', models.ForeignKey(limit_choices_to={'user_type': 'REVISOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='revisoes_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('projeto', 'revisor')},
            },
        ),
    ]
