# Generated by Django 5.2.7 on 2026-05-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaResumosAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='programa',
        ),
        migrations.AddField(
            model_name='projeto',
            name='programa',
            field=models.ManyToManyField(related_name='projetos', to='plataformaResumosAPP.programa'),
        ),
    ]
