# Generated by Django 5.2.7 on 2026-04-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaResumosAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.IntegerField(choices=[(1, 'Aluno'), (2, 'Professor'), (3, 'Coordenador')], default=1),
        ),
    ]
