# Generated by Django 5.2.7 on 2026-04-29 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaResumosAPP', '0002_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ODS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='projetosselecionados',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='projetosselecionados',
            name='revista',
        ),
        migrations.RemoveField(
            model_name='projetosselecionados',
            name='submissao',
        ),
        migrations.AlterUniqueTogether(
            name='projeto',
            unique_together={('aluno', 'turma')},
        ),
        migrations.AddField(
            model_name='projeto',
            name='justificativa_ods',
            field=models.TextField(default='Sem justificativa informada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='turma',
            field=models.ForeignKey(default='Sem justificativa informada', on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='plataformaResumosAPP.turma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revista',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default='Sem justificativa informada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='curso',
            field=models.CharField(default='Sem justificativa informada', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='disciplina',
            field=models.CharField(default='Sem justificativa informada', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='semestre',
            field=models.ForeignKey(default='Sem justificativa informada', on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='plataformaResumosAPP.semestre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projeto',
            name='referencia_projeto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revista',
            name='semestre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revista', to='plataformaResumosAPP.semestre'),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='semestre',
            field=models.IntegerField(choices=[(1, '1º Semestre'), (2, '2º Semestre')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ra',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='semestre',
            unique_together={('ano', 'semestre')},
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(limit_choices_to={'tipo_usuario': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='plataformaResumosAPP.turma')),
            ],
            options={
                'unique_together': {('aluno', 'turma')},
            },
        ),
        migrations.AddField(
            model_name='projeto',
            name='ods',
            field=models.ManyToManyField(related_name='projetos', to='plataformaResumosAPP.ods'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='programa',
            field=models.ForeignKey(default='Sem justificativa informada', on_delete=django.db.models.deletion.PROTECT, related_name='projetos', to='plataformaResumosAPP.programa'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjetoRevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revistas', to='plataformaResumosAPP.projeto')),
                ('revista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_revista', to='plataformaResumosAPP.revista')),
            ],
            options={
                'unique_together': {('revista', 'projeto')},
            },
        ),
        migrations.DeleteModel(
            name='ProjetoPorTurma',
        ),
        migrations.DeleteModel(
            name='ProjetosSelecionados',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='ods_projeto',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='professor_responsavel',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='programa_pepict',
        ),
    ]
